In [46]:
import pandas as pd
import glob
files = sorted(glob.glob("batting_part_*.csv"))
df = pd.concat((pd.read_csv(f) for f in files), ignore_index=True)
df.to_csv("all_batting.csv", index=False)

/var/folders/7y/c8_smbxj3v13gsc7ld8064h80000gn/T/ipykernel_49096/691190190.py:4: DtypeWarning: Columns (0: Unnamed: 39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in files), ignore_index=True)

In [4]:
df

,gid,id,team,b_lp,b_seq,stattype,b_pa,b_ab,b_r,b_h,...,Unnamed: 39,ARI201208110,wheer001,ARI,9,20120811,PHO01,h,WAS,1.6
0,HOU200404060,aardd001,SFN,9.0,4.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SDN200404080,aardd001,SFN,9.0,8.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SDN200404100,aardd001,SFN,9.0,5.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SFN200404140,aardd001,SFN,9.0,3.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SFN200404170,aardd001,SFN,7.0,2.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5746321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,SEA201708100,zycht001,SEA,NaN,20170810.0,SEA03,h,ANA,1.0
5746322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,SEA201708120,zycht001,SEA,NaN,20170812.0,SEA03,h,ANA,1.0
5746323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,SEA201708160,zycht001,SEA,NaN,20170816.0,SEA03,h,BAL,0.0
5746324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,TBA201708190,zycht001,SEA,NaN,20170819.0,STP01,v,TBA,0.0
5746325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,ASD194205240,zydoe101,ASD,6.0,19420524.0,CHI11,h,KCM,1.0

In [ ]:
df = df.loc[:, ~df.columns.str.startswith('Unnamed')]
print(df[df['gid'].isnull()].shape)
print(df[df['gid'].isnull()].head())

(746327, 85)
         gid   id team  b_lp  b_seq stattype  b_pa  b_ab  b_r  b_h  ...  y.1  \
4999999  NaN  NaN  NaN   NaN    NaN      NaN   NaN   NaN  NaN  NaN  ...    y
5000000  NaN  NaN  NaN   NaN    NaN      NaN   NaN   NaN  NaN  NaN  ...    y
5000001  NaN  NaN  NaN   NaN    NaN      NaN   NaN   NaN  NaN  NaN  ...    y
5000002  NaN  NaN  NaN   NaN    NaN      NaN   NaN   NaN  NaN  NaN  ...    y
5000003  NaN  NaN  NaN   NaN    NaN      NaN   NaN   NaN  NaN  NaN  ...    y

         ARI201208110  wheer001  ARI   9  20120811  PHO01    h  WAS  1.6
4999999           NaN       NaN  NaN NaN       NaN    NaN  NaN  NaN  NaN
5000000           NaN       NaN  NaN NaN       NaN    NaN  NaN  NaN  NaN
5000001           NaN       NaN  NaN NaN       NaN    NaN  NaN  NaN  NaN
5000002           NaN       NaN  NaN NaN       NaN    NaN  NaN  NaN  NaN
5000003           NaN       NaN  NaN NaN       NaN    NaN  NaN  NaN  NaN

[5 rows x 85 columns]

In [ ]:
df = df.loc[:, ~df.columns.str.startswith('Unnamed')]
df = df.dropna(subset=['gid'])
print(df.shape)
print(df.isnull().sum()[df.isnull().sum() > 0])

(4999999, 85)
b_lp         405212
b_seq        402149
b_pa          47704
b_ab          15116
b_r           13863
             ...
20120811    4999999
PHO01       4999999
h           4999999
WAS         4999999
1.6         4999999
Length: 73, dtype: int64

In [9]:
df

,gid,id,team,b_lp,b_seq,stattype,b_pa,b_ab,b_r,b_h,...,y.1,ARI201208110,wheer001,ARI,9,20120811,PHO01,h,WAS,1.6
0,HOU200404060,aardd001,SFN,9.0,4.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SDN200404080,aardd001,SFN,9.0,8.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SDN200404100,aardd001,SFN,9.0,5.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SFN200404140,aardd001,SFN,9.0,3.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SFN200404170,aardd001,SFN,7.0,2.0,value,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999994,NYA194108020,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999995,NYA194108031,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999996,NYA194108032,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999997,WS1194108040,sturj101,NYA,1.0,1.0,value,5.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999998,WS1194108050,sturj101,NYA,1.0,1.0,value,5.0,5.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df[df['b_ab'] > 0]
print(df.shape)

(4024655, 85)

In [11]:
df

,gid,id,team,b_lp,b_seq,stattype,b_pa,b_ab,b_r,b_h,...,y.1,ARI201208110,wheer001,ARI,9,20120811,PHO01,h,WAS,1.6
14,CHN200604290,aardd001,CHN,9.0,2.0,value,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,COL200608120,aardd001,CHN,9.0,2.0,value,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,HOU200806280,aardd001,BOS,9.0,3.0,value,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,ATL201507040,aardd001,ATL,9.0,2.0,value,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,CIN195404130,aaroh101,MLN,5.0,1.0,value,5.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999994,NYA194108020,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999995,NYA194108031,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999996,NYA194108032,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999997,WS1194108040,sturj101,NYA,1.0,1.0,value,5.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999998,WS1194108050,sturj101,NYA,1.0,1.0,value,5.0,5.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
print(df.columns.tolist())
print(df.shape)

['gid', 'id', 'team', 'b_lp', 'b_seq', 'stattype', 'b_pa', 'b_ab', 'b_r', 'b_h', 'b_d', 'b_t', 'b_hr', 'b_rbi', 'b_sh', 'b_sf', 'b_hbp', 'b_w', 'b_iw', 'b_k', 'b_sb', 'b_cs', 'b_gdp', 'b_xi', 'b_roe', 'dh', 'ph', 'pr', 'date', 'number', 'site', 'vishome', 'opp', 'win', 'loss', 'tie', 'gametype', 'box', 'pbp', 'eject', 'BOS194108061', 'sturj101', 'NYA', '1', '1.1', 'value', '4', '3', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '1.2', '0.9', '0.10', '0.11', '0.12', '1.3', '0.13', '0.14', '19410806', '1.4', 'BOS07', 'v', 'BOS', '0.15', '1.5', '0.16', 'regular', 'y', 'y.1', 'ARI201208110', 'wheer001', 'ARI', '9', '20120811', 'PHO01', 'h', 'WAS', '1.6']
(4024655, 85)

In [15]:
good_cols = ['gid', 'id', 'team', 'b_lp', 'b_seq', 'stattype', 'b_pa', 'b_ab', 'b_r', 'b_h', 
             'b_d', 'b_t', 'b_hr', 'b_rbi', 'b_sh', 'b_sf', 'b_hbp', 'b_w', 'b_iw', 'b_k', 
             'b_sb', 'b_cs', 'b_gdp', 'b_xi', 'b_roe', 'dh', 'ph', 'pr', 'date', 'number', 
             'site', 'vishome', 'opp', 'win', 'loss', 'tie', 'gametype', 'box', 'pbp', 'eject']

df = df[good_cols]
print(df.shape)
print(df.isnull().sum()[df.isnull().sum() > 0])

(4024655, 40)
b_lp         3654
b_seq        3577
b_pa        30967
b_r          1789
b_h           443
b_d          5522
b_t          5850
b_hr         4661
b_rbi       46645
b_sh         9000
b_sf       238734
b_hbp       10499
b_w          8420
b_iw       224043
b_k        112862
b_sb         8673
b_cs       250036
b_gdp      254586
b_xi        46075
b_roe      281549
dh        3899543
ph        3664399
pr        4010200
number     171135
box          4082
pbp        268026
eject     4017244
dtype: int64

In [16]:
df = df.drop(columns=['eject', 'pr', 'ph', 'dh', 'box', 'pbp'])
stat_cols = ['b_pa', 'b_r', 'b_h', 'b_d', 'b_t', 'b_hr', 'b_rbi', 'b_sh', 
             'b_sf', 'b_hbp', 'b_w', 'b_iw', 'b_k', 'b_sb', 'b_cs', 
             'b_gdp', 'b_xi', 'b_roe', 'b_lp', 'b_seq']
df[stat_cols] = df[stat_cols].fillna(0)
df['number'] = df['number'].fillna(0)
print(df.isnull().sum()[df.isnull().sum() > 0])

Series([], dtype: int64)

In [17]:
df

,gid,id,team,b_lp,b_seq,stattype,b_pa,b_ab,b_r,b_h,...,b_roe,date,number,site,vishome,opp,win,loss,tie,gametype
14,CHN200604290,aardd001,CHN,9.0,2.0,value,1.0,1.0,0.0,0.0,...,0.0,20060429.0,0.0,CHI11,h,MIL,0.0,1.0,0.0,regular
36,COL200608120,aardd001,CHN,9.0,2.0,value,1.0,1.0,0.0,0.0,...,0.0,20060812.0,0.0,DEN02,v,COL,0.0,1.0,0.0,regular
113,HOU200806280,aardd001,BOS,9.0,3.0,value,1.0,1.0,0.0,0.0,...,0.0,20080628.0,0.0,HOU03,v,HOU,0.0,1.0,0.0,regular
307,ATL201507040,aardd001,ATL,9.0,2.0,value,1.0,1.0,0.0,0.0,...,0.0,20150704.0,0.0,ATL02,h,PHI,1.0,0.0,0.0,regular
331,CIN195404130,aaroh101,MLN,5.0,1.0,value,5.0,5.0,0.0,0.0,...,0.0,19540413.0,0.0,CIN07,v,CIN,0.0,1.0,0.0,regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999994,NYA194108020,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,1.0,...,1.0,19410802.0,0.0,NYC16,h,SLA,1.0,0.0,0.0,regular
4999995,NYA194108031,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,0.0,...,0.0,19410803.0,1.0,NYC16,h,SLA,0.0,1.0,0.0,regular
4999996,NYA194108032,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,1.0,...,0.0,19410803.0,2.0,NYC16,h,SLA,0.0,1.0,0.0,regular
4999997,WS1194108040,sturj101,NYA,1.0,1.0,value,5.0,5.0,0.0,0.0,...,0.0,19410804.0,0.0,WAS09,v,WS1,1.0,0.0,0.0,regular
4999998,WS1194108050,sturj101,NYA,1.0,1.0,value,5.0,5.0,0.0,2.0,...,0.0,19410805.0,0.0,WAS09,v,WS1,0.0,1.0,0.0,regular

In [20]:
print(df['date'].astype(str).str[:4].min())

1898

In [26]:
df['year'] = df['date'].astype(int).astype(str).str[:4].astype(int)
df_early = df[df['year'] <= 1950]
df_mid = df[(df['year'] >= 1951) & (df['year'] <= 1990)]
df_contemporary = df[df['year'] >= 1991]
print(df_early.shape)
print(df_mid.shape)
print(df_contemporary.shape)

(1233120, 35)
(1302156, 35)
(1489379, 35)

In [28]:
df1 = pd.read_csv("mlb_teams.csv")

In [29]:
df1

,year,league_id,division_id,rank,games_played,home_games,wins,losses,division_winner,wild_card_winner,...,hits_allowed,homeruns_allowed,walks_allowed,strikeouts_by_pitchers,errors,double_plays,fielding_percentage,team_name,ball_park,home_attendance
0,1876,NL,NaN,4,70,NaN,39,31,NaN,NaN,...,732,7,104,77,442,42,0.860,Boston Red Caps,South End Grounds I,NaN
1,1876,NL,NaN,1,66,NaN,52,14,NaN,NaN,...,608,6,29,51,282,33,0.899,Chicago White Stockings,23rd Street Grounds,NaN
2,1876,NL,NaN,8,65,NaN,9,56,NaN,NaN,...,850,9,34,60,469,45,0.841,Cincinnati Reds,Avenue Grounds,NaN
3,1876,NL,NaN,2,69,NaN,47,21,NaN,NaN,...,570,2,27,114,337,27,0.888,Hartford Dark Blues,Hartford Ball Club Grounds,NaN
4,1876,NL,NaN,5,69,NaN,30,36,NaN,NaN,...,605,3,38,125,397,44,0.875,Louisville Grays,Louisville Baseball Park,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2779,2020,NL,C,3,58,27.0,30,28,N,Y,...,376,69,204,464,33,46,0.983,St. Louis Cardinals,Busch Stadium III,0.0
2780,2020,AL,E,1,60,29.0,40,20,Y,N,...,475,70,168,552,33,52,0.985,Tampa Bay Rays,Tropicana Field,0.0
2781,2020,AL,W,5,60,30.0,22,38,N,N,...,479,81,236,489,40,40,0.981,Texas Rangers,Globe Life Field,0.0
2782,2020,AL,E,3,60,26.0,32,28,N,Y,...,517,81,250,519,38,47,0.982,Toronto Blue Jays,Sahlen Field,0.0
2783,2020,NL,E,4,60,33.0,26,34,N,N,...,548,94,216,508,39,48,0.981,Washington Nationals,Nationals Park,0.0

In [38]:
df_teams = df1.dropna(subset=['team_name'])
df_teams = df1[df1['games_played'] > 0]
print(df1.shape)
print(df1.isnull().sum()[df1.isnull().sum() > 0])

(2784, 41)
division_id              1346
home_games                228
division_winner          1374
wild_card_winner         2010
league_winner              28
world_series_winner       248
strikeouts_by_batters      16
stolen_bases               76
caught_stealing           708
batters_hit_by_pitch     1066
sacrifice_flies          1370
home_attendance           108
dtype: int64

In [39]:
flag_cols = ['division_winner', 'wild_card_winner', 'league_winner', 'world_series_winner']
df_teams[flag_cols] = df_teams[flag_cols].fillna('N')
num_cols = ['home_games', 'strikeouts_by_batters', 'stolen_bases', 'caught_stealing', 
            'batters_hit_by_pitch', 'sacrifice_flies', 'home_attendance']
df_teams[num_cols] = df_teams[num_cols].fillna(0)
df_teams['division_id'] = df_teams['division_id'].fillna('Unknown')
print(df_teams.isnull().sum()[df_teams.isnull().sum() > 0])

Series([], dtype: int64)

In [40]:
df

,gid,id,team,b_lp,b_seq,stattype,b_pa,b_ab,b_r,b_h,...,date,number,site,vishome,opp,win,loss,tie,gametype,year
14,CHN200604290,aardd001,CHN,9.0,2.0,value,1.0,1.0,0.0,0.0,...,20060429.0,0.0,CHI11,h,MIL,0.0,1.0,0.0,regular,2006
36,COL200608120,aardd001,CHN,9.0,2.0,value,1.0,1.0,0.0,0.0,...,20060812.0,0.0,DEN02,v,COL,0.0,1.0,0.0,regular,2006
113,HOU200806280,aardd001,BOS,9.0,3.0,value,1.0,1.0,0.0,0.0,...,20080628.0,0.0,HOU03,v,HOU,0.0,1.0,0.0,regular,2008
307,ATL201507040,aardd001,ATL,9.0,2.0,value,1.0,1.0,0.0,0.0,...,20150704.0,0.0,ATL02,h,PHI,1.0,0.0,0.0,regular,2015
331,CIN195404130,aaroh101,MLN,5.0,1.0,value,5.0,5.0,0.0,0.0,...,19540413.0,0.0,CIN07,v,CIN,0.0,1.0,0.0,regular,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999994,NYA194108020,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,1.0,...,19410802.0,0.0,NYC16,h,SLA,1.0,0.0,0.0,regular,1941
4999995,NYA194108031,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,0.0,...,19410803.0,1.0,NYC16,h,SLA,0.0,1.0,0.0,regular,1941
4999996,NYA194108032,sturj101,NYA,1.0,1.0,value,4.0,4.0,0.0,1.0,...,19410803.0,2.0,NYC16,h,SLA,0.0,1.0,0.0,regular,1941
4999997,WS1194108040,sturj101,NYA,1.0,1.0,value,5.0,5.0,0.0,0.0,...,19410804.0,0.0,WAS09,v,WS1,1.0,0.0,0.0,regular,1941
4999998,WS1194108050,sturj101,NYA,1.0,1.0,value,5.0,5.0,0.0,2.0,...,19410805.0,0.0,WAS09,v,WS1,0.0,1.0,0.0,regular,1941

In [41]:
print(df_teams.isnull().sum().sum())

0

In [42]:
df_teams['year'].min(), df_teams['year'].max()

(np.int64(1876), np.int64(2020))

In [43]:
df_teams_early = df_teams[df_teams['year'] <= 1950]
df_teams_mid = df_teams[(df_teams['year'] >= 1951) & (df_teams['year'] <= 1990)]
df_teams_contemporary = df_teams[df_teams['year'] >= 1991]

print(df_teams_early.shape)
print(df_teams_mid.shape)
print(df_teams_contemporary.shape)

(1028, 41)
(874, 41)
(882, 41)

In [ ]:
df_yearly = df.groupby('year').agg(
    total_ab=('b_ab', 'sum'),
    total_hits=('b_h', 'sum'),
    total_hr=('b_hr', 'sum'),
    total_runs=('b_r', 'sum'),
    total_rbi=('b_rbi', 'sum'),
    total_walks=('b_w', 'sum'),
    total_k=('b_k', 'sum'),
    total_sb=('b_sb', 'sum'),
).reset_index()
df_teams_yearly = df_teams.groupby('year').agg(
    total_wins=('wins', 'sum'),
    total_losses=('losses', 'sum'),
    total_runs_scored=('runs_scored', 'sum'),
    total_hr=('homeruns', 'sum'),
    total_errors=('errors', 'sum'),
    total_attendance=('home_attendance', 'sum'),
    num_teams=('team_name', 'count')
).reset_index()

print(df_yearly.head())
print(df_teams_yearly.head())

   year  total_ab  total_hits  total_hr  total_runs  total_rbi  total_walks  \
0  1898   55224.0     15022.0     263.0      8134.0     6703.0       4525.0
1  1899   55188.0     15591.0     312.0      8508.0     7017.0       4266.0
2  1900   34786.0      9721.0     235.0      5239.0     4309.0       2664.0
3  1901   71176.0     19245.0     433.0     10235.0     8311.0       5141.0
4  1902   70090.0     18790.0     340.0      9155.0     7501.0       5024.0

   total_k  total_sb
0   3015.0    1908.0
1   2811.0    2401.0
2   2191.0    1525.0
3   5231.0    2665.0
4   4965.0    2518.0
   year  total_wins  total_losses  total_runs_scored  total_hr  total_errors  \
0  1876         257           257               3066        40          3124
1  1877         177           177               2040        24          1858
2  1878         180           180               1904        23          1778
3  1879         316           316               3409        58          3127
4  1880         332           332               3191        62          2949

   total_attendance  num_teams
0               0.0          8
1               0.0          6
2               0.0          6
3               0.0          8
4               0.0          8